### ISSUE TITLE
Skip Link on Second Page of Registration

### ISSUE THREAD

**Issue by JQTNguyen** [badcamp/badcamp-2020#21]
Skip link on the second page of registration needs to be fixed.

**Comment by JQTNguyen** [comment]
@mel-miller and @sean-e-dietrich: ^

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3163110

**Comment by JQTNguyen** [comment]
Per 8/3/20 Website Meeting, please change the "Skip" link into a Button instead, and style accordingly.
