### ISSUE TITLE
Remove All Caps from Content Regions

### ISSUE THREAD

**Issue by JQTNguyen** [badcamp/badcamp-2020#24]
Remove instances of CSS implemented ALL CAPS text transformations from content regions, as this presents accessibility issues.

**Examples:**

- User Registration Pages
- Headings (e.g.: Sponsor Page at https://2020.badcamp.org/sponsors)

**Comment by AmyJuneH** [comment]
This was merged with https://github.com/badcamp/badcamp-2020/pull/22
