### ISSUE TITLE
Session Views CSV files

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2020#30]
Can we have two outputs for CSV files for sessions?

FOr the user:
- One with userID
- One with name

**Comment by AmyJuneH** [comment]
First CSV view:
User ID(s)
Session Title
Description
Length
Track
Topics

Second CSV view:
User NAME(s)
Session Title
Description
Length
Track
Topics
Identity(s)

**Comment by mel-miller** [comment]
Working on this today.

**Comment by mel-miller** [comment]
Done. I've sent @AmyJuneH the links via Slack.

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3168517
