### ISSUE TITLE
CTA button request

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2020#37]
It would be great to have a main CTA button at the top to encourage people to submit sessions (and not have to be logged in to see that CTA, like you have to be now)

**Comment by mel-miller** [comment]
If we add it, this button will direct them to log in before they can submit a session. We will probably also need to add text to the login page that lets them know to register if they don't already have an account. Is that what you were thinking? @AmyJuneH

**Comment by AmyJuneH** [comment]
yep.

**Comment by mel-miller** [comment]
We should close this one or shelve it for next time.

**Comment by AmyJuneH** [comment]
Closing this issue.
