### ISSUE TITLE
Email alias for Code of Conduct contacts

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2020#48]
Motivation:
People who want to report incidents against the BADCamp Code of Contact should be able to report incidents only to the code of conduct points of contact, not the whole organizer team.

Can we set you the email alias `coc@badcamp.org` and have the emails forward to only AMyJune and Kelly?

Thanks.

**Comment by sean-e-dietrich** [comment]
This was registered and created.
