### ISSUE TITLE
Visual Indicate which session will be Live Captioned

### ISSUE THREAD

**Issue by AmyJuneH** [badcamp/badcamp-2020#51]
Add a checkbox on the backend for which sessions will be live captioned.

Visually have the CC logo appear on node and schedule.

**Comment by mel-miller** [comment]
@AmyJuneH -- In addition to the icon, do you have boilerplate language you'd like to attach to the sessions that have been designated for live captioning? Or are you going to to that within Hopin?

**Comment by AmyJuneH** [comment]
https://www.drupal.org/project/badcamp/issues/3179467
